const allowedOrigins=new Set(['https://yousoft.site','https://www.yousoft.site','http://localhost:8000','http://127.0.0.1:8000']);
const allowedShopTypes=new Set(['grocery','clothing','cosmetics','spare_parts','repair_shop','other']);
function corsHeaders(origin:string|null){const value=origin&&allowedOrigins.has(origin)?origin:'https://yousoft.site';return{'Access-Control-Allow-Origin':value,'Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}}
function json(body:unknown,status:number,origin:string|null){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders(origin),'Content-Type':'application/json; charset=utf-8'}})}
function clean(value:unknown,maxLength:number){return typeof value==='string'?value.trim().slice(0,maxLength):''}
async function rest(path:string,init:RequestInit){const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)throw new Error('Supabase service configuration is missing');return fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})}})}
async function updateSheetState(id:string,state:string,error:string|null){await rest(`store_soft_leads?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({sheet_sync_status:state,sheet_synced_at:state==='synced'?new Date().toISOString():null,sheet_sync_error:error,updated_at:new Date().toISOString()})})}
async function syncToSheet(lead:Record<string,unknown>){const url=Deno.env.get('GOOGLE_SHEETS_WEBHOOK_URL'),secret=Deno.env.get('GOOGLE_SHEETS_WEBHOOK_SECRET');if(!url||!secret){await updateSheetState(String(lead.id),'not_configured','Google Sheets webhook is not configured');return}try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({secret,lead}),redirect:'follow'});const result=await response.json().catch(()=>({}));if(!response.ok||result.ok!==true)throw new Error(`Sheets webhook returned ${response.status}`);await updateSheetState(String(lead.id),'synced',null)}catch(error){const message=error instanceof Error?error.message.slice(0,500):'Unknown Sheets error';await updateSheetState(String(lead.id),'failed',message)}}
Deno.serve(async(request:Request)=>{const origin=request.headers.get('Origin');if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(origin)});if(request.method!=='POST')return json({ok:false,error:'method_not_allowed'},405,origin);if(!origin||!allowedOrigins.has(origin))return json({ok:false,error:'origin_not_allowed'},403,origin);if(Number(request.headers.get('Content-Length')||0)>16384)return json({ok:false,error:'payload_too_large'},413,origin);
let body:Record<string,unknown>;try{body=await request.json()}catch(_){return json({ok:false,error:'invalid_json'},400,origin)}if(clean(body.website,200))return json({ok:true},200,origin);const startedAt=Number(body.form_started_at||0);if(!Number.isFinite(startedAt)||Date.now()-startedAt<800)return json({ok:false,error:'form_submitted_too_quickly'},400,origin);
const name=clean(body.name,80),email=clean(body.email,254).toLowerCase(),shopType=clean(body.shop_type,40);if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!allowedShopTypes.has(shopType))return json({ok:false,error:'invalid_fields'},422,origin);
const row={name,email,email_normalized:email,shop_type:shopType,language:clean(body.language,5)||'ar',source:clean(body.source,120),medium:clean(body.medium,120),campaign:clean(body.campaign,200),content:clean(body.content,200),term:clean(body.term,200),referrer:clean(body.referrer,500),landing_page:clean(body.landing_page,500)};
const inserted=await rest('store_soft_leads',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});let lead:Record<string,unknown>|undefined;if(inserted.ok){lead=(await inserted.json())[0]}else if(inserted.status===409){const existing=await rest(`store_soft_leads?email_normalized=eq.${encodeURIComponent(email)}&select=*`,{method:'GET'});if(!existing.ok)return json({ok:false,error:'storage_failed'},500,origin);lead=(await existing.json())[0]}else{console.error('Lead insert failed',inserted.status,await inserted.text());return json({ok:false,error:'storage_failed'},500,origin)}if(!lead)return json({ok:false,error:'storage_failed'},500,origin);await syncToSheet(lead);return json({ok:true,lead_id:lead.id},200,origin)});
