(function(){
'use strict';
var endpoint='https://blczhiusyvpkxrktgwng.supabase.co/functions/v1/submit-store-soft-lead';
var formStartedAt=Date.now(),currentLanguage='ar';
var copies={
ar:{brandTagline:'تسيير بسيط لمحلك',help:'تحتاج مساعدة؟',eyebrow:'نسخة تجريبية لأصحاب المحلات في الجزائر',title:'خلّي البيع يمشي،<br><span>حتى بلا إنترنت.</span>',intro:'Store Soft يجمع الكاشي، المخزون، الكريدي والتقارير في تطبيق واحد بسيط على الهاتف والكمبيوتر.',offlineTitle:'يخدم بلا إنترنت',offlineText:'البيع ما يوقفش كي تروح الشبكة',devicesTitle:'Android وWindows',devicesText:'نفس المحل على الهاتف أو الكمبيوتر',languageTitle:'بالعربية والفرنسية',languageText:'كلمات بسيطة يفهمها صاحب المحل',supportTitle:'نساعدك في التثبيت',supportText:'إذا احتجت أي مساعدة، نتواصل معك مباشرة على واتساب.',available:'الطلبات مفتوحة',formTitle:'اطلب رابط التحميل',formIntro:'معلومات قصيرة فقط. سنضيف بريدك إلى Google Play ثم نرسل لك الرابط.',nameLabel:'الاسم',namePlaceholder:'مثال: محمد',emailLabel:'بريد Google Play',emailHint:'استعمل البريد المرتبط بـ Google Play في هاتفك.',phoneLabel:'رقم واتساب / الهاتف',shopLabel:'نوع المحل',shopPlaceholder:'اختر نوع المحل',shopGrocery:'مواد غذائية / سوبرات',shopClothing:'ملابس وأحذية',shopCosmetics:'مواد تجميل',shopParts:'قطع غيار',shopRepair:'محل تصليح',shopOther:'نشاط آخر',submit:'أرسل لي رابط التحميل',submitting:'جاري إرسال الطلب…',privacyBefore:'بإرسال الطلب، توافق على استعمال معلوماتك للتواصل حول Store Soft فقط.',privacyLink:'سياسة الخصوصية',terms:'شروط الاستخدام',successTitle:'تم استلام طلبك',successText:'سيتم إرسال رابط تحميل Store Soft إلى بريدك الإلكتروني.',sentTo:'البريد المسجّل',successNote:'تأكد أن هذا هو نفس البريد المستعمل في Google Play.',editEmail:'تصحيح البريد',stepsEyebrow:'ماذا يحدث بعد الطلب؟',stepsTitle:'ثلاث خطوات، والتجربة عندك.',stepOneTitle:'نستلم طلبك',stepOneText:'معلوماتك تظهر مباشرة في قائمة المتابعة.',stepTwoTitle:'نضيف بريدك',stepTwoText:'نسمح لبريدك بالدخول إلى نسخة Google Play.',stepThreeTitle:'يصلك رابط التثبيت',stepThreeText:'نرسله عبر البريد، ونتابع معك على واتساب.',required:'هذا الحقل مطلوب.',invalidEmail:'أدخل بريدًا إلكترونيًا صحيحًا.',invalidPhone:'أدخل رقم هاتف صحيحًا.',generalError:'تعذّر إرسال الطلب. تحقق من الإنترنت وحاول مرة أخرى.'},
fr:{brandTagline:'La gestion simple du magasin',help:'Besoin d’aide ?',eyebrow:'Essai pour les commerçants algériens',title:'Continuez à vendre,<br><span>même sans Internet.</span>',intro:'Store Soft réunit caisse, stock, crédit et rapports dans une application simple sur Android et Windows.',offlineTitle:'Fonctionne hors ligne',offlineText:'La vente continue sans connexion',devicesTitle:'Android et Windows',devicesText:'Sur téléphone ou ordinateur',languageTitle:'Arabe et français',languageText:'Des mots simples pour le commerçant',supportTitle:'Nous vous aidons à installer',supportText:'Si nécessaire, nous vous accompagnons directement sur WhatsApp.',available:'Demandes ouvertes',formTitle:'Demander le lien',formIntro:'Quatre informations seulement. Nous ajoutons votre e-mail à Google Play puis nous envoyons le lien.',nameLabel:'Nom',namePlaceholder:'Exemple : Mohamed',emailLabel:'E-mail Google Play',emailHint:'Utilisez l’e-mail associé à Google Play sur votre téléphone.',phoneLabel:'WhatsApp / téléphone',shopLabel:'Type de magasin',shopPlaceholder:'Choisissez votre activité',shopGrocery:'Alimentation / supérette',shopClothing:'Vêtements et chaussures',shopCosmetics:'Cosmétiques',shopParts:'Pièces détachées',shopRepair:'Atelier de réparation',shopOther:'Autre activité',submit:'Recevoir le lien de téléchargement',submitting:'Envoi de la demande…',privacyBefore:'En envoyant cette demande, vous acceptez que vos informations servent uniquement au suivi Store Soft.',privacyLink:'Confidentialité',terms:'Conditions',successTitle:'Demande reçue',successText:'Le lien de téléchargement Store Soft sera envoyé à votre adresse e-mail.',sentTo:'E-mail enregistré',successNote:'Vérifiez qu’il s’agit du même e-mail que celui de Google Play.',editEmail:'Corriger l’e-mail',stepsEyebrow:'Que se passe-t-il ensuite ?',stepsTitle:'Trois étapes avant l’essai.',stepOneTitle:'Nous recevons la demande',stepOneText:'Vos informations arrivent immédiatement dans notre suivi.',stepTwoTitle:'Nous ajoutons votre e-mail',stepTwoText:'Votre compte reçoit l’accès à la version Google Play.',stepThreeTitle:'Vous recevez le lien',stepThreeText:'Nous l’envoyons par e-mail et assurons le suivi sur WhatsApp.',required:'Ce champ est obligatoire.',invalidEmail:'Saisissez une adresse e-mail valide.',invalidPhone:'Saisissez un numéro de téléphone valide.',generalError:'La demande n’a pas pu être envoyée. Vérifiez votre connexion et réessayez.'}
};
var form=document.getElementById('leadForm'),button=document.getElementById('submitButton'),submitLabel=button.querySelector('span'),formView=document.getElementById('formView'),successView=document.getElementById('successView'),submitError=document.getElementById('submitError'),languageSwitch=document.getElementById('languageSwitch');
function copy(key){return copies[currentLanguage][key]}
function setLanguage(language){currentLanguage=language;var isArabic=language==='ar';document.documentElement.lang=language;document.documentElement.dir=isArabic?'rtl':'ltr';languageSwitch.textContent=isArabic?'FR':'ع';languageSwitch.setAttribute('aria-label',isArabic?'Afficher en français':'عرض الصفحة بالعربية');document.querySelectorAll('[data-copy]').forEach(function(el){var value=copy(el.getAttribute('data-copy'));if(value!==undefined)el.innerHTML=value});document.querySelectorAll('[data-copy-placeholder]').forEach(function(el){el.placeholder=copy(el.getAttribute('data-copy-placeholder'))});clearErrors()}
function clearErrors(){['name','email','phone','shopType'].forEach(function(id){var input=document.getElementById(id);input.removeAttribute('aria-invalid');document.getElementById(id+'Error').textContent=''});submitError.textContent=''}
function fieldError(id,message){document.getElementById(id).setAttribute('aria-invalid','true');document.getElementById(id+'Error').textContent=message}
function validate(values){clearErrors();var valid=true;if(!values.name){fieldError('name',copy('required'));valid=false}if(!values.email){fieldError('email',copy('required'));valid=false}else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email)){fieldError('email',copy('invalidEmail'));valid=false}if(!values.phone){fieldError('phone',copy('required'));valid=false}else if(values.phone.replace(/\D/g,'').length<8){fieldError('phone',copy('invalidPhone'));valid=false}if(!values.shop_type){fieldError('shopType',copy('required'));valid=false}return valid}
function campaignData(){var params=new URLSearchParams(window.location.search);return{source:params.get('utm_source')||'',medium:params.get('utm_medium')||'',campaign:params.get('utm_campaign')||'',content:params.get('utm_content')||'',term:params.get('utm_term')||'',referrer:document.referrer||'',landing_page:window.location.href}}
function trackMetaLead(){if(typeof window.fbq==='function')window.fbq('track','Lead',{content_name:'Store Soft download request'})}
languageSwitch.addEventListener('click',function(){setLanguage(currentLanguage==='ar'?'fr':'ar')});
form.addEventListener('submit',async function(event){event.preventDefault();var data=new FormData(form);var values={name:String(data.get('name')||'').trim(),email:String(data.get('email')||'').trim().toLowerCase(),phone:String(data.get('phone')||'').trim(),shop_type:String(data.get('shop_type')||''),website:String(data.get('website')||''),form_started_at:formStartedAt,language:currentLanguage};if(!validate(values))return;Object.assign(values,campaignData());button.disabled=true;submitLabel.textContent=copy('submitting');try{var response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});var result=await response.json().catch(function(){return{}});if(!response.ok||!result.ok)throw new Error(result.error||'submit_failed');document.getElementById('submittedEmail').textContent=values.email;formView.hidden=true;successView.hidden=false;trackMetaLead();successView.focus()}catch(_){submitError.textContent=copy('generalError')}finally{button.disabled=false;submitLabel.textContent=copy('submit')}});
document.getElementById('editEmail').addEventListener('click',function(){successView.hidden=true;formView.hidden=false;document.getElementById('email').focus()});document.getElementById('year').textContent=new Date().getFullYear();setLanguage('ar');
})();
